#!/bin/sh

mkdir -p opk
cp ./race-od.dge opk/race-od
cp ./race.png opk/icon.png

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=race-od
Comment=NeoGeo Pocker Emulator
Exec=race-od %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default.rs90.desktop

mksquashfs ./opk race-rs90.opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
